import TechDraw
from PySide import QtCore
DRAW=OUT/'drawings';pages=json.loads((DRAW/'drawing_pages.json').read_text())

if 'SwitchDrawingSheets' in App.listDocuments():App.closeDocument('SwitchDrawingSheets')
TD=App.newDocument('SwitchDrawingSheets');TD.Label='Switch · A3 矢量图纸与尺寸参考'
TDPAGES=[];DIM_CHECKS=[]
for page in pages:
    no=page['number'];pg=TD.addObject('TechDraw::DrawPage',f'Sheet{no:02d}');pg.Label=f'{no:02d} · '+page['title'];TDPAGES.append(pg)
    temp=TD.addObject('TechDraw::DrawSVGTemplate',f'Template{no:02d}');temp.Template=str(DRAW/'source'/f'TechDraw_Template_{no:02d}.svg');pg.Template=temp
    symbol=TD.addObject('TechDraw::DrawViewSymbol',f'VectorSheet{no:02d}');symbol.Symbol=(DRAW/page['svg']).read_text();symbol.Scale=1;symbol.X=210;symbol.Y=156;pg.addView(symbol)
    symbol.addProperty('App::PropertyString','SourceDescription','Trace');symbol.SourceDescription='Visible-line BRep projection and exact planar sections of Switch_Complete / Switch_Exploded; regenerated by drawing_geometry.py.'
    # Lightweight native dimensions retain measurable endpoint references without repeating the full HLR workload.
    for j,dim in enumerate(page['dimensions'],1):
        spec=next(v for v in page['views'] if v['name']==dim['view']);q=rotation(spec['normal'],spec['up']).inverted()
        p1=q.multVec(vec(*dim['p1'])-vec(*spec['center']));p2=q.multVec(vec(*dim['p2'])-vec(*spec['center']));p1.z=p2.z=0
        src=TD.addObject('Part::Feature',f'ReferenceLine{no:02d}_{j}');src.Shape=Part.makeLine(p1,p2);src.Visibility=False
        view=TD.addObject('TechDraw::DrawViewPart',f'ReferenceView{no:02d}_{j}');view.Source=[src];view.Direction=vec(0,0,1);view.XDirection=vec(1,0,0);view.ScaleType='Custom';view.Scale=spec['scale'];pg.addView(view)
        view.X=12+spec['x']+((p1.x+p2.x)/2)*spec['scale'];view.Y=297-34-spec['y']+((p1.y+p2.y)/2)*spec['scale']
        TD.recompute()
        deadline=time.time()+8
        while len(view.getVisibleVertexes())<2 and time.time()<deadline:
            loop=QtCore.QEventLoop();QtCore.QTimer.singleShot(20,loop.quit);loop.exec_();Gui.updateGui()
        assert len(view.getVisibleVertexes())==2
        n=TD.addObject('TechDraw::DrawViewDimension',f'Dimension{no:02d}_{j}');n.Type='DistanceX' if dim['axis']=='x' else 'DistanceY';n.References2D=[(view,('Vertex0','Vertex1'))];pg.addView(n)
        n.X=12+dim['label_position'][0];n.Y=297-34-dim['label_position'][1];n.Label=dim['label']+' mm · '+spec['name'];n.ShowUnits=True;TD.recompute()
        value=n.getRawValue();assert abs(value-dim['value_mm'])<1e-5,(no,j,value,dim['value_mm'])
        n.addProperty('App::PropertyString','ReferenceNote','Trace');n.ReferenceNote='Measurement endpoints sampled from this model revision; rerun drawing_geometry.py after model edits.'
        view.Visibility=False;n.Visibility=False
        DIM_CHECKS.append({'sheet':no,'dimension':n.Name,'expected_mm':dim['value_mm'],'measured_mm':value,'pass':True})
    TD.recompute();Gui.updateGui()
    TD.saveAs(str(OUT/'Switch_Drawings.FCStd'))
    (OUT/'reports/native_drawing_progress.json').write_text(json.dumps({'stage':'saved','page':no,'time':time.time()}))
invalid=[o.Name for o in TD.Objects if 'Invalid' in o.State];assert not invalid,invalid
RESULT={'pass':True,'pages':12,'native_dimension_references':len(DIM_CHECKS),'checks':DIM_CHECKS,'presentation':'Self-contained SVG drawing sheets plus native measurable dimension references; full parametric 3D history is in Switch_Complete.FCStd','file':TD.FileName,'invalid':invalid}
(OUT/'reports/native_drawings_audit.json').write_text(json.dumps(RESULT,ensure_ascii=False,indent=2))
App.setActiveDocument(D.Name);visible(HANDHELD_GROUPS)
RESULT={k:v for k,v in RESULT.items() if k!='checks'}
